<div id="currency-converter">
    <h2>Currency Exchange Converter</h2>
    <select id="from"></select>
    <button id="swap"><span class="swap-symbol">&#x21C4;</span> Swap</button>
    <select id="to"></select>
    <div id="rate"></div>
    <canvas id="chart"></canvas>
</div>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type="text/javascript" src="<?= $block->getViewFileUrl('Techm_CurrencyConverter::js/converter.js') ?>"></script>
